version: '2.3'
services:
  blog-apache:
    container_name: 'blog-apache'
    build:
      context: 'docker/apache'
    environment:
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
    volumes:
      - '.:/var/www/html'
    ports:
      - '8080:80'
